const firstNames = ["Alex", "Jamie", "Jordan", "Taylor", "Casey", "Riley", "Quinn", "Morgan", "Skyler", "Peyton", "Haruto", "Yuto", "Sota", "Yuki", "Hayato", "Haruki", "Ryusei", "Kaito", "Yuma", "Sosuke"];
const lastNames = ["Smith", "Johnson", "Brown", "Williams", "Jones", "Miller", "Davis", "García", "Rodriguez", "Martinez", "Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Kato"];
const words = ["Descubrimiento", "Futuro", "Tecnología", "Naturaleza", "Misterio", "Aventura", "Ciencia", "Historia", "Arte", "Viaje", "Innovación", "Universo", "Cultura", "Descubrimiento", "Creatividad", "Exploración", "Revolución", "Sueños", "Progreso", "Inspiración"]
const phrases = [
    "El descubrimiento sorprendente en la jungla dejó a los científicos asombrados. Los investigadores se encontraron con una especie de planta nunca antes vista que podría tener propiedades medicinales revolucionarias. Este hallazgo podría cambiar la industria farmacéutica para siempre.",
    "Las innovaciones en tecnología están cambiando la forma en que vivimos. Desde la inteligencia artificial hasta la realidad virtual, estas tecnologías están transformando nuestra sociedad y la manera en que interactuamos con el mundo. Las empresas están compitiendo por liderar en este nuevo mundo digital.",
    "Un viaje inesperado llevó a un descubrimiento histórico. Un grupo de arqueólogos se aventuró en una expedición en busca de antiguas ruinas y, para su sorpresa, encontraron una ciudad perdida que había estado enterrada durante siglos. Este hallazgo arqueológico está atrayendo la atención de todo el mundo.",
    "El arte de la antigüedad todavía tiene secretos por revelar. Cada obra maestra antigua es como un rompecabezas que los historiadores del arte están ansiosos por descifrar, desvelando los misterios y significados ocultos detrás de cada pincelada. La apreciación del arte antiguo sigue siendo una parte importante de nuestra cultura.",
    "La naturaleza nos sorprende con su diversidad y complejidad. Los ecosistemas del mundo albergan una variedad asombrosa de flora y fauna, recordándonos constantemente la belleza y fragilidad de nuestro planeta. La conservación de la naturaleza es esencial para las generaciones futuras.",
    "El futuro de la ciencia se ve más brillante que nunca. Con avances constantes en campos como la biotecnología, la astronomía y la energía renovable, el potencial para resolver los desafíos globales es emocionante. Los científicos están trabajando incansablemente para mejorar nuestro mundo.",
    "El misterio detrás de la historia antigua sigue cautivando a muchos. Los enigmas de civilizaciones desaparecidas, como los egipcios o los mayas, continúan intrigando a los investigadores y a aquellos apasionados por la arqueología. La historia antigua nos conecta con nuestro pasado.",
    "La aventura de explorar nuevos mundos está apenas comenzando. Con el avance de la tecnología espacial, la humanidad se encuentra en el umbral de explorar planetas lejanos y descubrir lo que yace más allá de nuestro sistema solar. La exploración espacial nos abre un mundo de posibilidades.",
    "La música tiene el poder de tocar nuestras almas y evocar emociones profundas. Cada nota y melodía nos transporta a un lugar único, donde nuestros sentimientos se entrelazan con las notas musicales, creando una experiencia inolvidable.",
    "La literatura es una ventana a mundos imaginarios que despiertan nuestra creatividad. Los libros nos permiten explorar universos inexplorados, conocer personajes fascinantes y sumergirnos en historias que nos hacen reflexionar sobre la vida y la humanidad.",
    "La amistad verdadera es un tesoro que debemos valorar y cuidar toda la vida. Los amigos son aquellos que están ahí en los momentos buenos y malos, brindando apoyo incondicional y compartiendo risas y lágrimas a lo largo del camino.",
    "El trabajo en equipo es fundamental para alcanzar metas y superar desafíos. Cuando personas con diferentes habilidades y perspectivas se unen en un esfuerzo colaborativo, pueden lograr resultados sorprendentes que van más allá de lo que podrían lograr por sí solas.",
    "El aprendizaje constante nos permite crecer y evolucionar como individuos. Cada día es una oportunidad para adquirir nuevos conocimientos, desarrollar habilidades y descubrir aspectos desconocidos de nosotros mismos, enriqueciendo nuestra vida.",
    "El amor es un sentimiento que puede cambiar nuestras vidas de formas inesperadas. Cuando encontramos a alguien que nos hace sentir amados y aceptados tal como somos, experimentamos una profunda conexión que puede darle un nuevo significado a nuestra existencia.",
    "La belleza de la naturaleza se encuentra en los detalles más pequeños. Desde la delicadeza de una flor hasta la majestuosidad de un paisaje montañoso, la naturaleza nos brinda constantemente momentos de asombro y admiración.",
    "La paciencia es una virtud que nos ayuda a enfrentar las adversidades con calma. En tiempos de incertidumbre y desafío, la paciencia nos permite mantener la serenidad y buscar soluciones con sabiduría y determinación.",
    "El respeto mutuo es la base de relaciones saludables y armoniosas. Cuando tratamos a los demás con respeto y consideración, construimos la confianza y el entendimiento necesarios para mantener relaciones sólidas y duraderas.",
    "La empatía nos permite comprender y conectar con las experiencias de los demás. Al ponerse en el lugar de otra persona y sentir lo que siente, podemos fortalecer nuestros lazos humanos y construir puentes de comprensión y compasión."
];

module.exports = { firstNames, lastNames, phrases, words };